apiVersion: v1
kind: Service
metadata:
  name: daftpunk-redis
  labels:
    context: daftpunk
spec:
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31379
  type: NodePort
  selector:
    app: redis
    context: daftpunk
